# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="Creative Commons BY-NC-ND"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ADDSynth/Overpowered-Technology-1.19.4/issues" #optional






[[mods]]
modId="addsynth_energy"
version="1.0"
displayName="ADDSynth Energy"
displayURL="http://www.gyrostudiostechnology.com/minecraft/mods/addsynth_energy/index.html"
logoFile="addsynth_energy_logo.png"
credits="Mojang, and the Forge Development Team"
authors="ADDSynth"
description="Library by ADDSynth, for ADDSynth's mods. Adds Energy Wire, a Generator, an Electric Furnace, and the Universal Energy Interface."
[[dependencies.addsynth_energy]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.4.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.addsynth_energy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.addsynth_energy]]
    modId="addsynthcore"
    mandatory=true
    versionRange="[1,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.addsynth_energy]]
    modId="addsynth_materials"
    mandatory=true
    versionRange="[1,)"
    ordering="BEFORE"
    side="BOTH"


[[mods]]
modId="overpowered_technology" #mandatory
version="6" #mandatory
displayName="Overpowered Technology" #mandatory
updateJSONURL="http://www.gyrostudiostechnology.com/minecraft/mods/overpowered/update.json" #optional
displayURL="http://www.gyrostudiostechnology.com/minecraft/mods/overpowered/index.html" #optional
logoFile="overpowered_technology_logo.png" #optional
credits="Mojang, and the Forge Development Team" #optional
authors="ADDSynth" #optional
description="This mod adds a bunch of really cool science and tech stuff."

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.overpowered_technology]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.4.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.overpowered_technology]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.overpowered_technology]]
    modId="addsynthcore"
    mandatory=true
    versionRange="[1.0,2.0)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.overpowered_technology]]
    modId="addsynth_energy"
    mandatory=true
    versionRange="[1,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.overpowered_technology]]
    modId="addsynth_materials"
    mandatory=true
    versionRange="[1.0,2.0)"
    ordering="BEFORE"
    side="BOTH"
